### PR TITLE
fix: pagination returns less than the page size when decryption fails

### LINKED ISSUE #1382: Add pagination to the Request Node /getTransactionsByChannelId endpoint

### PR DESCRIPTION
**Pull request by rodrigopavezi**
## Problem 
First pagination implementation has performance issues and it will not work for request which cannot be decrypted. For instance when requesting 10 encrypted requests there might be requests that cannot be decrypted so it would return less than 10. That would cause confusion to the consumer.

## Changes
Move the pagination logic to upper level so it will return the right number of valid requests.

Fixes #1382 

## Release Notes

- **Refactor**
    - Removed pagination parameters from multiple data access methods across various components.
    - Simplified channel and transaction retrieval processes.
    - Updated method signatures to focus on core retrieval parameters.

- **Types**
    - Modified type definitions to remove pagination-related properties.
    - Enhanced metadata structures to support optional pagination information.

- **Performance**
    - Streamlined data retrieval methods.
    - Removed complex pagination logic from multiple services.

- **New Features**
    - Introduced a new property for pagination information in the metadata of certain methods.
    - Enhanced handling of responses to ensure consistent data structures across methods.

### CODE REVIEW

File: packages/thegraph-data-access/src/subgraph-client.ts [hunk 1]
```diff
@@ -85,15 +67,10 @@ export class SubgraphClient implements StorageTypes.IIndexer {
...
     return {
       transactions: indexedTransactions,
       blockNumber: _meta.block.number,
-      pagination: {
-        page: effectivePage,
-        pageSize: effectivePageSize,
-        total: indexedTransactions.length,
-        hasMore: skip + effectivePageSize < indexedTransactions.length,
-      },
     };
```
[the remark this answers is not in the document]
Comment (rodrigopavezi) [reply packages/thegraph-data-access/src/subgraph-client.ts:74]: Thanks for the suggestion but I will not add it now

File: packages/types/src/request-logic-types.ts [hunk 2]
```diff
@@ -98,6 +98,7 @@ export interface IRequestLogicReturnWithConfirmation extends EventEmitter {
 export interface IReturnMeta {
   transactionManagerMeta: any;
   ignoredTransactions?: any[];
+  pagination?: any;
```
[the remark this answers is not in the document]
Comment (rodrigopavezi) [reply packages/types/src/request-logic-types.ts:101]: I will leave like this as all the other types are any to allow flexibility

File: packages/request-client.js/src/http-data-access.ts [hunk 3]
```diff
@@ -110,10 +110,8 @@ export default class HttpDataAccess extends CombinedDataAccess {
   public async getChannelsByTopic(
     topic: string,
     updatedBetween?: DataAccessTypes.ITimestampBoundaries,
-    page?: number,
-    pageSize?: number,
   ): Promise<DataAccessTypes.IReturnGetChannelsByTopic> {
-    return await this.reader.getChannelsByTopic(topic, updatedBetween, page, pageSize);
+    return await this.reader.getChannelsByTopic(topic, updatedBetween);
```
[the remark this answers is not in the document]
Comment (rodrigopavezi) [reply packages/request-client.js/src/http-data-access.ts:114]: We don't need pagination on the http data access anymore

File: packages/types/src/data-access-types.ts [hunk 4]
```diff
@@ -97,9 +92,9 @@ export interface IReturnGetChannelsByTopic {
     transactionsStorageLocation: {
       [key: string]: string[];
     };
+    pagination?: any;
```
[the remark this answers is not in the document]
Comment (rodrigopavezi) [reply packages/types/src/data-access-types.ts:95]: I will not change that now

File: packages/request-client.js/test/api/request-network.test.ts [hunk 5]
```diff
@@ -263,14 +264,15 @@
...
 
       const requestnetwork = new RequestNetwork({ dataAccess: mockDataAccessWithTxs });
-      const requests: Request[] = await requestnetwork.fromMultipleIdentities(
+      const result = await requestnetwork.fromMultipleIdentities(
         [TestData.payee.identity],
         undefined,
         {
           page: 1,
           pageSize: 10,
         },
```
[the remark this answers is not in the document]
Comment (rodrigopavezi) [reply packages/request-client.js/test/api/request-network.test.ts:273]: That is wrong

File: packages/request-client.js/test/api/request-network.test.ts [hunk 6]
```diff
@@ -143,14 +144,11 @@
...
-        undefined,
-        {
-          page: 1,
-          pageSize: 10,
-        },
-      );
+      const result = await requestnetwork.fromIdentity(TestData.payee.identity, undefined, {
+        page: 1,
+        pageSize: 10,
+      });
```
[the remark this answers is not in the document]
Comment (rodrigopavezi) [reply packages/request-client.js/test/api/request-network.test.ts:150]: That is also wrong

File: packages/transaction-manager/src/transaction-manager.ts [hunk 7]
```diff
@@ -236,31 +227,144 @@ export default class TransactionManager implements TransactionTypes.ITransaction
...
+          result.transactions[channelId] =
+            cleaned.transactions as unknown as TransactionTypes.ITransaction[];
+          result.ignoredTransactions[channelId] =
+            cleaned.ignoredTransactions as unknown as TransactionTypes.ITransaction[];
+        }
+      } catch (error) {
+        console.warn(`Failed to decrypt channel ${channelId}:`, error);
+        result.transactions[channelId] = [];
+        result.ignoredTransactions[channelId] = [];
+      }
```
[the remark this answers is not in the document]
Comment (rodrigopavezi) [reply packages/transaction-manager/src/transaction-manager.ts:294]: I will not change that now. Thanks

File: packages/request-client.js/test/api/request-network.test.ts [hunk 8]
```diff
@@ -107,6 +107,7 @@ describe('api/request-network', () => {
             meta: {
               [TestData.actionRequestId]: [],
               [TestData.actionRequestIdSecondRequest]: [],
+              transactionsStorageLocation: {},
             },
             result: {
               transactions: {
```
[the remark this answers is not in the document]
Comment (rodrigopavezi) [reply packages/request-client.js/test/api/request-network.test.ts:111]: Fixed

**Comment by MantisClone** [comment]
@coderabbitai full review

File: packages/request-client.js/test/api/request-network.test.ts [hunk 9]
```diff
@@ -99,14 +99,13 @@ describe('api/request-network', () => {
...
           updatedBetween?: DataAccessTypes.ITimestampBoundaries,
-          page?: number,
-          pageSize?: number,
         ): Promise<any> {
           expect(topic).toBe('01f1a21ab419611dbf492b3136ac231c8773dc897ee0eb5167ef2051a39e685e76');
           return {
             meta: {
               [TestData.actionRequestId]: [],
               [TestData.actionRequestIdSecondRequest]: [],
+              transactionsStorageLocation: {},
```
Comment (MantisClone) [inline packages/request-client.js/test/api/request-network.test.ts:108]: What's this?

File: packages/integration-test/test/node-client.test.ts [hunk 10]
```diff
@@ -273,7 +273,7 @@ describe('Request client using a request node', () => {
     await waitForConfirmation(requestDataCancel);
 
     // get requests without boundaries
-    let requests = await requestNetwork.fromTopic(topicsRequest1and2[0]);
+    let requests: Request[] = (await requestNetwork.fromTopic(topicsRequest1and2[0])) as Request[];
```
Comment (MantisClone) [inline packages/integration-test/test/node-client.test.ts:276]: I wonder if we should check the type with an `if` or even assert the type with an `expect` instead of casting. Especially if you see this test as example usage code. That said, I recognize we're trying to ship this fast - I'm open to dissent.

Comment (MantisClone) [reply packages/integration-test/test/node-client.test.ts:276]: Or like you did in packages/request-client.js/test/index.test.ts

```ts
      const response = await requestNetwork.fromTopic('my amazing test topic');
      const requests = Array.isArray(response) ? response : response.requests;
      expect(requests).not.toHaveLength(0);
```

File: packages/request-logic/src/request-logic.ts [hunk 11]
```diff
@@ -640,14 +641,18 @@ export default class RequestLogic implements RequestLogicTypes.IRequestLogic {
...
 
           // add the transactionManagerMeta
           (finalResult.meta.transactionManagerMeta || []).push(
             requestAndMeta.transactionManagerMeta,
           );
+
+          finalResult.meta.pagination = {
+            ...finalResult.meta.pagination,
+            ...requestAndMeta.pagination,
+          };
```
Comment (MantisClone) [inline packages/request-logic/src/request-logic.ts:655]: Can you explain what this is doing?  I think you're keeping a running total of the pagination data, overwriting the old pagination with the new pagination.

File: packages/request-node/src/request/getChannelsByTopic.ts [hunk 12]
```diff
@@ -15,29 +15,19 @@ export default class GetChannelHandler {
    * @param dataAccess data access layer
    */
   async handler(clientRequest: Request, serverResponse: Response): Promise<void> {
-    // Retrieves data access layer
-    let transactions;
+    const { updatedBetween, topic } = clientRequest.query;
```
[the remark this answers is not in the document]
Comment (MantisClone) [reply packages/request-node/src/request/getChannelsByTopic.ts:18]: This is outside the scope of the current PR. @coderabbitai Please create an issue to implement this in a different PR :pray:  Please note that the same error handling should be applied to all endpoints that accept the `updatedBetween` argument.

File: packages/thegraph-data-access/src/queries.ts [hunk 13]
```diff
@@ -108,3 +106,14 @@ export const GetTransactionByDataHashQuery = gql`
...
+export const GetTransactionsByTopicsCount = gql`
+  query GetTransactionsByTopicsCount($topics: [String!]!) {
+    ${metaQueryBody}
+    channels(where: { topics_contains: $topics }) {
+      transactions {
+        id
+      }
+    }
+  }
+`;
```
Comment (MantisClone) [inline packages/thegraph-data-access/src/queries.ts:119]: What is this?

File: packages/request-client.js/test/api/request-network.test.ts (hunk 9 above)
Comment (rodrigopavezi) [reply packages/request-client.js/test/api/request-network.test.ts:108]:
```
export interface IReturnGetTransactions {
  /** meta information */
  meta: {
    /** location of the transactions (follow the position of the result.transactions) */
    transactionsStorageLocation: string[];
    /** meta-data from the layer below */
    storageMeta?: StorageTypes.IEntryMetadata[];
  };
  /** result of the execution */
  result: { transactions: ITimestampedTransaction[] };
}
```

It is part of the meta information

File: packages/transaction-manager/src/transaction-manager.ts [hunk 14]
```diff
@@ -236,31 +227,144 @@ export default class TransactionManager implements TransactionTypes.ITransaction
...
         const cleaned = await this.channelParser.decryptAndCleanChannel(
           channelId,
-          resultGetTx.result.transactions[channelId],
+          channel.filteredTransactions,
         );
 
-        // await for the accumulator promise at the end to parallelize the calls to decryptAndCleanChannel()
-        const accumulator: any = await accumulatorPromise;
+        // When paginating, include channels based on validity
+        if (page !== undefined || pageSize !== undefined) {
```
Comment (MantisClone) [inline packages/transaction-manager/src/transaction-manager.ts:278]: Will this fail if only `page` is defined but not `pageSize`, or vice versa?  Is there validation somewhere to ensure both are defined?

File: packages/thegraph-data-access/src/queries.ts (hunk 13 above)
Comment (rodrigopavezi) [reply packages/thegraph-data-access/src/queries.ts:119]: I reverted some code I believe it came with it. Removing it

File: packages/transaction-manager/src/transaction-manager.ts (hunk 14 above)
Comment (MantisClone) [reply packages/transaction-manager/src/transaction-manager.ts:278]: I found the validation on line 301.

New question: Should this be `&&` instead of `||`?

File: packages/integration-test/test/node-client.test.ts (hunk 10 above)
Comment (rodrigopavezi) [reply packages/integration-test/test/node-client.test.ts:276]: Sure, I will fix it

File: packages/request-logic/src/request-logic.ts (hunk 11 above)
Comment (rodrigopavezi) [reply packages/request-logic/src/request-logic.ts:655]: You can see above that the reduce is merging all the requests and meta in one object.

File: packages/transaction-manager/src/transaction-manager.ts (hunk 14 above)
Comment (rodrigopavezi) [reply packages/transaction-manager/src/transaction-manager.ts:278]: It should be AND. Fixing that

File: packages/transaction-manager/src/transaction-manager.ts [hunk 15]
```diff
@@ -236,31 +227,144 @@ export default class TransactionManager implements TransactionTypes.ITransaction
...
+      channelsToProcess.map(async (channelId) => {
+        const cleaned = await this.channelParser.decryptAndCleanChannel(
+          channelId,
+          resultGetTx.result.transactions[channelId],
+        );
+
+        result.transactions[channelId] =
+          cleaned.transactions as unknown as TransactionTypes.ITransaction[];
+        result.ignoredTransactions[channelId] =
+          cleaned.ignoredTransactions as unknown as TransactionTypes.ITransaction[];
```
Comment (MantisClone) [inline packages/transaction-manager/src/transaction-manager.ts:325]: Why do you need to cast `as unknown as TransactionTypes.ITransaction[]` here?

File: packages/transaction-manager/src/transaction-manager.ts [hunk 16]
```diff
@@ -236,31 +227,144 @@ export default class TransactionManager implements TransactionTypes.ITransaction
...
+        ignoredTransactions: result.ignoredTransactions as unknown as Record<
+          string,
+          TransactionTypes.IIgnoredTransaction[]
+        >,
+      },
+      result: {
+        transactions: result.transactions as unknown as Record<
+          string,
+          TransactionTypes.ITimestampedTransaction[]
+        >,
```
Comment (MantisClone) [inline packages/transaction-manager/src/transaction-manager.ts:360]: Why do you need to cast `as unknown` here?

Comment (rodrigopavezi) [reply packages/transaction-manager/src/transaction-manager.ts:356]: Good catch. Fixed it!

File: packages/integration-test/test/node-client.test.ts [hunk 17]
```diff
@@ -341,9 +342,9 @@ describe('Request client using a request node', () => {
     await new Promise((r) => setTimeout(r, 1500));
 
     // get requests with boundaries
-    const requests = await requestNetwork.fromIdentity(payerSmartContract, {
+    const requests = (await requestNetwork.fromIdentity(payerSmartContract, {
       from: timestampCreation,
-    });
+    })) as Request[];
```
[the remark this answers is not in the document]
Comment (rodrigopavezi) [reply packages/integration-test/test/node-client.test.ts:348]: sure

File: packages/transaction-manager/test/index.test.ts [hunk 18]
```diff
@@ -1260,39 +1258,39 @@ describe('index', () => {
 
       const ret = await transactionManager.getChannelsByTopic(extraTopics[0]);
 
-      // 'ret.result is wrong'
+      // Update expectations to match actual behavior
```
Comment (MantisClone) [inline packages/transaction-manager/test/index.test.ts:1261]: Nice change. But I think this comment seems more like a commit message and can be removed.

File: packages/integration-test/test/node-client.test.ts
Comment (MantisClone) [inline packages/integration-test/test/node-client.test.ts:1]: Looks good. Do you think it's missing any tests?

**Review by MantisClone — APPROVED** [review]
Approved :+1: 

@rodrigopavezi and I briefly discussed adding more tests. I leave it to @rodrigopavezi to determine how much additional testing to add.

File: packages/transaction-manager/test/index.test.ts [hunk 19]
```diff
@@ -1500,22 +1497,24 @@ describe('index', () => {
...
       });
-      // 'ret.meta is wrong'
-      expect(ret.meta).toEqual(
-        expect.objectContaining({
-          dataAccessMeta: fakeMetaDataAccessGetReturnWithEncryptedTransaction.meta,
-          ignoredTransactions: {
-            [channelId]: [null],
-            [channelId2]: [null],
+
+      // Update the metadata expectation to include all fields
```
[the remark this answers is not in the document]
Comment (rodrigopavezi) [reply packages/transaction-manager/test/index.test.ts]: sure

File: packages/transaction-manager/test/index.test.ts (hunk 18 above)
Comment (rodrigopavezi) [reply packages/transaction-manager/test/index.test.ts]: yeap

File: packages/transaction-manager/test/index.test.ts [hunk 20]
```diff
@@ -1564,17 +1574,366 @@ describe('index', () => {
...
+      expect(Object.keys(result.result.transactions)).toHaveLength(2);
+      expect(result.result.transactions).toHaveProperty(channelId);
+      expect(result.result.transactions).toHaveProperty(channelId2);
+      expect(result.meta.dataAccessMeta.pagination).toEqual({
+        total: 2,
+        page: 1,
+        pageSize: 2,
+        hasMore: false,
+      });
+    });
```
[the remark this answers is not in the document]
Comment (rodrigopavezi) [reply packages/transaction-manager/test/index.test.ts]: Fixed

**Review by aimensahnoun — APPROVED** [review]

**Review by aimensahnoun — CHANGES_REQUESTED** [review]
Checks are failing

File: packages/transaction-manager/src/transaction-manager.ts [hunk 21]
```diff
@@ -236,31 +228,146 @@ export default class TransactionManager implements TransactionTypes.ITransaction
...
+          };
+        }
+      }),
+    );
+
+    // Filter out null values and get valid channels
+    const validChannels = processedChannels
+      .filter(
+        (channel): channel is NonNullable<typeof channel> =>
+          channel !== null && (page !== undefined ? channel.isValid : true),
```
[the remark this answers is not in the document]
Comment (rodrigopavezi) [reply packages/transaction-manager/src/transaction-manager.ts:302]: That is the intended behavior

File: packages/transaction-manager/src/transaction-manager.ts [hunk 22]
```diff
@@ -236,31 +228,146 @@ export default class TransactionManager implements TransactionTypes.ITransaction
...
+        transactions: result.transactions,
+      },
     };
   }
+
+  private isValidChannel(cleaned: { transactions: any[]; ignoredTransactions: any[] }): boolean {
+    return (
+      cleaned.transactions && cleaned.transactions.length > 0 && cleaned.transactions[0] !== null
+    );
+  }
```
[the remark this answers is not in the document]
Comment (rodrigopavezi) [reply packages/transaction-manager/src/transaction-manager.ts]: Fixed

**Review by sstefdev — APPROVED** [review]

**Review by aimensahnoun — APPROVED** [review]
