### PR TITLE
fix(ethereum-storage): OldNonce error, wait for 1 confirmation when submitting hashes

### LINKED ISSUE #1074: Fix OldNonce error in request-node
# Problem
Under heavy load, the request-node throws OldNonce errors.

```
 ERROR: persistTransaction error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32010,\"message\":\"OldNonce, Current nonce: 78948, nonce of rejected tx: 78941\"},\"id\":110}", error={"code":-32010}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f9015a648301345d846346d65b846346d66382d9bf94268c146afb4790902ee26a6d2d3aff968623ec80880162ea854d0fc000b8e451a58abb000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000002e516d523367465872444661544d554e7646754e424e3546647153505a724b7a353174547a4247435437734b38725600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000631c001a0767a5d9a2598da01707c0aaa254d04d195559a9d39121f63bb9c4fadf9dac1c8a06c06e3723d151ac93475d89c6deed7c1c444804cf8e642b68803388e64a1372f\"],\"id\":110,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://holy-proud-morning.xdai.quiknode.pro/<...omitted...>/", code=SERVER_ERROR, version=web/5.5.0)
```

# Theory
When multiple persistTransaction requests come in at the same time, they are submitted with the same nonce. After the first one is validated, the subsequent ones error due to old nonce. If true, solution will be to serialize transactions.

### PR DESCRIPTION
**Pull request by MantisClone**
Fixes #1074
Fixes [dw-97](https://app.dework.xyz/request-network/development-56861?taskId=0065cfa3-bf4b-49f4-9140-ec18c2693173)

Changes:
* Wait for 1 block confirmation when submitting hashes on-chain. EVM-like blockchains can experience chain reorgs. Usually they are only 1 block in depth. For example, Gnosis Chain experiences a [1-block reorg every few minutes](https://gnosisscan.io/blocks_forked?p=1) so it's important to wait for 2 block confirmations before submitting the next transaction.

### CODE REVIEW

**Review by kevindavee — APPROVED** [review]

File: packages/ethereum-storage/src/ethereum-storage-ethers.ts [hunk 1]
```diff
@@ -75,7 +75,7 @@ export class EthereumStorageEthers implements StorageTypes.IStorageWrite {
     this.logger.debug(`TX ${tx.hash} submitted, waiting for confirmation...`);
 
     void tx
-      .wait()
+      .wait(1)
```
Comment (benjlevesque) [inline packages/ethereum-storage/src/ethereum-storage-ethers.ts:78]: this is the default value

https://github.com/ethers-io/ethers.js/blob/ba967875f71019d367606f2b0bfae27879723a57/src.ts/providers/provider.ts#L822

File: packages/request-node/README.md [hunk 2]
```diff
@@ -148,6 +148,10 @@ A Node can be deployed by anyone. Users interested by running their own node can
 
 ### Installation
 
+#### Install IPFS Kubo (go-ipfs)
+
+https://docs.ipfs.tech/install/command-line/#install-ipfs-kubo
```
Comment (benjlevesque) [inline packages/request-node/README.md:153]: I recommend using docker to run IPFS

File: packages/ethereum-storage/src/ethereum-storage-ethers.ts (hunk 1 above)
Comment (MantisClone) [reply packages/ethereum-storage/src/ethereum-storage-ethers.ts:78]: I think I'm off-by-one but that the concept is still valid. I'll increase it to 2 confirmations because Gnosis Chain frequently experiences 1 block reorgs.

Comment (benjlevesque) [reply packages/ethereum-storage/src/ethereum-storage-ethers.ts:78]: can you make it configurable by env var?

File: packages/request-node/README.md (hunk 2 above)
Comment (MantisClone) [reply packages/request-node/README.md:153]: Ah okay. I'll recommend IPFS Docker near the top of the README. But I'll still include the Kubo link lower down where it describes using `ipfs init`

File: packages/ethereum-storage/src/ethereum-storage-ethers.ts (hunk 1 above)
Comment (MantisClone) [reply packages/ethereum-storage/src/ethereum-storage-ethers.ts:78]: Good idea. The reorg frequency differs between chains.

File: packages/request-node/README.md (hunk 2 above)
Comment (MantisClone) [reply packages/request-node/README.md]: I moved the Kubo installation down to the bottom of the README where `ipfs-init` script is used.  

I don't know the best place to recommend IPFS Docker so I'm going to leave that part out for now.

File: packages/ethereum-storage/src/config.ts [hunk 3]
```diff
@@ -17,6 +17,7 @@ const config = {
     retryDelay: 0,
     safeGasPriceLimit: '500000000000',
     transactionPollingTimeout: 300,
+    blockConfirmations: 2,
```
Comment (benjlevesque) [inline packages/ethereum-storage/src/config.ts:20]: I don't think this is ever used

File: packages/ethereum-storage/src/config.ts [hunk 4]
```diff
@@ -85,6 +86,14 @@ export function getDefaultEthereumGasPrice(): BigNumber {
   return BigNumber.from(process?.env?.GAS_PRICE_DEFAULT || config.ethereum.gasPriceDefault);
 }
 
+/**
+ * Retrieve from config the default number of block confirmations to wait before considering a transaction successful
+ * @returns the number of block confirmations
+ */
+export function getDefaultEthereumBlockConfirmations(): number {
```
Comment (benjlevesque) [inline packages/ethereum-storage/src/config.ts:93]: same

File: packages/request-node/src/config.ts [hunk 5]
```diff
@@ -119,6 +119,18 @@ export function getGasPriceMin(): BigNumber | undefined {
...
 
+/**
+ * Get the number of block confirmations to wait before considering a transaction successful
+ * @returns the number of block confirmations
+ */
+export function getBlockConfirmations(): number {
+  return (
+    (argv.blockConfirmations && Number(argv.blockConfirmations)) ||
+    (process.env.BLOCK_CONFIRMATIONS && Number(process.env.BLOCK_CONFIRMATIONS)) ||
+    defaultValues.ethereumStorage.ethereum.blockConfirmations
```
Comment (benjlevesque) [inline packages/request-node/src/config.ts:130]: this is never set, see at the top of this file

Comment (MantisClone) [reply packages/request-node/src/config.ts:130]: Fixed.

File: packages/ethereum-storage/src/config.ts (hunk 3 above)
Comment (MantisClone) [reply packages/ethereum-storage/src/config.ts:20]: Fixed, see comment below.

**Review by benjlevesque — APPROVED** [review]

**Review by olivier7delf — APPROVED** [review]
