### PR TITLE
fix: remove node-localstorage, add StorageProvider interface

### LINKED ISSUE #1501: Remove `node-localstorage`

### PR DESCRIPTION
**Pull request by rodrigopavezi**
## Description of the changes

Fixes #1501 

refactor: remove node-localstorage dependency and update storage handling in LitProvider

- Removed node-localstorage from package.json and yarn.lock.
- Updated LitProvider to use a new StorageProvider interface.
- Refactored storage handling logic to improve compatibility with Node.js.
- Enhanced the RequestNetwork class to include getter and setter for cipherProvider.
- Modified GraphQL queries to improve transaction retrieval logic and pagination settings.

This change streamlines storage management and enhances the overall architecture of the project.

## Release Notes

- **New Features**
  - Enhanced `LitProvider` class with improved type safety for storage providers.
  - Introduced optional `cipherProvider` functionality in the `RequestNetwork` class, allowing better management of encryption features.

- **Improvements**
  - Updated GraphQL queries to focus on transactions directly, improving data retrieval efficiency.
  - Increased pagination limits for transaction retrieval, allowing for larger data sets to be handled in a single request.

- **Bug Fixes**
  - Adjusted Jest test timeouts to ensure tests complete successfully without premature termination.

### CODE REVIEW

File: packages/thegraph-data-access/src/subgraph-client.ts [hunk 1]
```diff
@@ -19,8 +19,8 @@ export class SubgraphClient implements StorageTypes.IIndexer {
   private graphql: GraphQLClient;
   public readonly endpoint: string;
 
-  private readonly DEFAULT_PAGE_SIZE = 10;
-  private readonly MAX_PAGE_SIZE = 100;
+  private readonly DEFAULT_PAGE_SIZE = 100;
```
Comment (aimensahnoun) [inline packages/thegraph-data-access/src/subgraph-client.ts:22]: This still caps the requests at 100 requests, so if a wallet has more they won't be able to get the rest.

At least currently.

Comment (rodrigopavezi) [reply packages/thegraph-data-access/src/subgraph-client.ts:22]: Yes, but if they are encrypted it could cause performance issues. So I am attempting to accommodate for both use cases.

Comment (rodrigopavezi) [reply packages/thegraph-data-access/src/subgraph-client.ts:22]: It will definitely force clients to start using pagination

**Review by aimensahnoun — APPROVED** [review]

File: packages/data-access/src/data-read.ts [hunk 2]
```diff
@@ -113,25 +112,33 @@ export class DataAccessRead implements DataAccessTypes.IDataRead {
...
+    const channels = [...new Set(filteredTransactions.map((x) => x.channelId))];
 
+    // Get all transactions for these channels
     const filteredTxs = transactions.filter((tx) => channels.includes(tx.channelId));
+
+    // Apply pagination to the filtered results
+    const start = ((page || 1) - 1) * (pageSize || filteredTxs.length);
+    const end = start + (pageSize || filteredTxs.length);
+    const paginatedTxs = filteredTxs.slice(start, end);
+
```
[the remark this answers is not in the document]
Comment (MantisClone) [reply packages/data-access/src/data-read.ts:134]: Based on the comments in the code, this behavior is intentional.

**Comment by MantisClone** [comment]
The ethereum-storage tests flaked so I'm re-running them. 
The integration-tests failed due to a change in the pagination logic - @rodrigopavezi please take a look.

File: packages/data-access/src/data-read.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (rodrigopavezi) [reply packages/data-access/src/data-read.ts]: I have reverted this changes

**Review by MantisClone — APPROVED** [review]
